---
title: "code"
author: "Shahar Chaikin"
date: "7/20/2023"
output: html_document
---

This code presents the analyses used in NATECOLEVOL-23050986

#Packages
```{r}
library(tidyverse)
library(glmmTMB)
```

#Load the data
```{r}
data=read.csv("data.csv")
```

#main effect
The relationship between population trends and range shift velocities.
Population trends (slopes) based on linear models with scaled abundance.
```{r}
test_main_effect=glmmTMB(data=data,
formula=slope~shift_of_min_sm+
  (1|family)+
  (1|study_id),
family = 'gaussian',
weights =sqrt_n)
#Model Summary
summary(test_main_effect)
MuMIn::r.squaredGLMM(test_main_effect)
#Model diagnostics
sjPlot::plot_model(test_main_effect,type="diag")
sjPlot::plot_model(test_main_effect,type="eff",show.data = T)
```

##remove extreme range shift velocities
```{r}
#shift of minimum sm
quantile(data$shift_of_min_sm)[[4]]
IQR=quantile(data$shift_of_min_sm)[[4]]-quantile(data$shift_of_min_sm)[[2]]
min=quantile(data$shift_of_min_sm)[[2]]-(IQR*1.5)
max=quantile(data$shift_of_min_sm)[[4]]+(IQR*1.5)

test_main_effect_rm_ex_sh=glmmTMB::glmmTMB(data=data %>% filter(shift_of_min_sm<=max & shift_of_min_sm>=min),
formula=slope~shift_of_min_sm+
  (1|family)+
  (1|study_id),
family = 'gaussian',
weights =sqrt_n) 
#Model Summary
summary(test_main_effect_rm_ex_sh)
MuMIn::r.squaredGLMM(test_main_effect_rm_ex_sh)
#Model diagnostics
sjPlot::plot_model(test_main_effect_rm_ex_sh,type="diag")
sjPlot::plot_model(test_main_effect_rm_ex_sh,type="eff")
```

##Poleward side range shift velocities


##Equatorward side range shift velocities

